export * from "./app/api/endpoints/auth-company/auth-company";
export * from "./app/api/endpoints/auth-university/auth-university";
export * from "./app/api/endpoints/auth-admin/auth-admin";
export * from "./app/api/endpoints/company/company";
export * from "./app/api/endpoints/university/university";
export * from "./app/api/endpoints/admin/admin";
export * from "./app/api/endpoints/files/files";
export * from "./app/api/models";
export * from "./app/api/endpoints/invite/invite";
