/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyDetailCompanyDtoCosmetic } from "./adminCompanyDetailCompanyDtoCosmetic";

export interface AdminCompanyDetailCompanyDto {
  id: string;
  registered_name: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  tin: string | null;
  /** @nullable */
  company_type: string | null;
  /** @nullable */
  registered_address: string | null;
  /** @nullable */
  cosmetic: AdminCompanyDetailCompanyDtoCosmetic;
  /** @nullable */
  email_verified: boolean | null;
  /** @nullable */
  is_deactivated: boolean | null;
  created_at: string;
}
