/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminReviewHistoryItemDtoStatus } from "./adminReviewHistoryItemDtoStatus";
import type { AdminReviewHistoryItemDtoDocumentReviewDetails } from "./adminReviewHistoryItemDtoDocumentReviewDetails";
import type { AdminReviewHistoryItemDtoMaterial } from "./adminReviewHistoryItemDtoMaterial";
import type { AdminReviewHistoryDocumentDto } from "./adminReviewHistoryDocumentDto";

export interface AdminReviewHistoryItemDto {
  id: string;
  /** @nullable */
  status: AdminReviewHistoryItemDtoStatus;
  created_at: string;
  /** @nullable */
  reviewed_at: string | null;
  /** @nullable */
  reviewer_email: string | null;
  /** @nullable */
  rejection_reason: string | null;
  /** @nullable */
  document_review_details: AdminReviewHistoryItemDtoDocumentReviewDetails;
  /** @nullable */
  approval_expires_at: string | null;
  /** @nullable */
  material?: AdminReviewHistoryItemDtoMaterial;
  documents?: AdminReviewHistoryDocumentDto[];
}
