/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyDetailCompanyDto } from "./adminCompanyDetailCompanyDto";
import type { AdminCompanyDocItemDto } from "./adminCompanyDocItemDto";
import type { AdminCompanyDetailVerificationDto } from "./adminCompanyDetailVerificationDto";
import type { AdminCompanyDetailReviewHistoryItemDto } from "./adminCompanyDetailReviewHistoryItemDto";

export interface AdminCompanyDetailResponse {
  success: boolean;
  message?: string;
  company: AdminCompanyDetailCompanyDto;
  documents: AdminCompanyDocItemDto[];
  verification: AdminCompanyDetailVerificationDto;
  reviewHistory: AdminCompanyDetailReviewHistoryItemDto[];
}
