/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyDetailVerificationDtoStatus } from "./adminCompanyDetailVerificationDtoStatus";

export interface AdminCompanyDetailVerificationDto {
  status: AdminCompanyDetailVerificationDtoStatus;
  /** @nullable */
  rejectionReason: string | null;
}
