/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyListItemDto } from "./adminCompanyListItemDto";

export interface AdminCompaniesResponse {
  success: boolean;
  message?: string;
  companies: AdminCompanyListItemDto[];
}
