/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminUniversityAccountDto } from "./adminUniversityAccountDto";

export interface AdminUniversityListItemDto {
  id: string;
  registered_name: string;
  /** @nullable */
  is_deactivated: boolean | null;
  university_accounts: AdminUniversityAccountDto[];
}
