/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyReviewItemDtoDocumentReviewDetails } from "./adminCompanyReviewItemDtoDocumentReviewDetails";
import type { AdminCompanyReviewItemDtoCompany } from "./adminCompanyReviewItemDtoCompany";

export interface AdminCompanyReviewItemDto {
  id: string;
  /** @nullable */
  status: string | null;
  created_at: string;
  /** @nullable */
  reviewed_at: string | null;
  /** @nullable */
  reviewed_by_id: string | null;
  /** @nullable */
  rejection_reason: string | null;
  /** @nullable */
  approval_expires_at: string | null;
  /** @nullable */
  history_snapshot_id: string | null;
  company_id: string;
  /** @nullable */
  document_review_details?: AdminCompanyReviewItemDtoDocumentReviewDetails;
  /** @nullable */
  company: AdminCompanyReviewItemDtoCompany;
}
