/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCompanyDetailCompanyDto } from "./adminCompanyDetailCompanyDto";
import type { AdminReviewHistoryItemDto } from "./adminReviewHistoryItemDto";

export interface AdminCompanyReviewDetailResponse {
  success: boolean;
  message?: string;
  company: AdminCompanyDetailCompanyDto;
  history: AdminReviewHistoryItemDto[];
  /** @nullable */
  openReviewId: string | null;
}
