/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminCreateUniversityResponseUniversity } from "./adminCreateUniversityResponseUniversity";

export interface AdminCreateUniversityResponse {
  success: boolean;
  message?: string;
  university: AdminCreateUniversityResponseUniversity;
}
