/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { AdminUniversityPartnersResponseUniversity } from "./adminUniversityPartnersResponseUniversity";
import type { UniversityPartnerListItemDto } from "./universityPartnerListItemDto";
import type { UniversityBlacklistEntryDto } from "./universityBlacklistEntryDto";

export interface AdminUniversityPartnersResponse {
  success: boolean;
  message?: string;
  university: AdminUniversityPartnersResponseUniversity;
  partners: UniversityPartnerListItemDto[];
  blacklist: UniversityBlacklistEntryDto[];
}
