/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type BulkInviteTargetDtoType =
  (typeof BulkInviteTargetDtoType)[keyof typeof BulkInviteTargetDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkInviteTargetDtoType = {
  registered: "registered",
  legacy: "legacy",
} as const;
