/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface CompanyCreateQueuedMoaDto {
  id: string;
  company_id: string;
  university_id: string;
  template_id: string;
  rep_name: string;
  rep_title: string;
  status: string;
  /** @nullable */
  failure_reason: string | null;
  created_at: string;
}
