/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyRequestableTemplateDto } from "./companyRequestableTemplateDto";
import type { CompanyRequestableTemplatesResponseUniversity } from "./companyRequestableTemplatesResponseUniversity";

export interface CompanyRequestableTemplatesResponse {
  success: boolean;
  message?: string;
  templates: CompanyRequestableTemplateDto[];
  /** @nullable */
  university: CompanyRequestableTemplatesResponseUniversity;
  requestable?: boolean;
}
