/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyDocumentDto } from "./companyDocumentDto";

export interface CompanyDocumentsResponse {
  success: boolean;
  message?: string;
  documents: CompanyDocumentDto[];
  all: CompanyDocumentDto[];
}
