/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyDtoCosmetic } from "./companyDtoCosmetic";

export interface CompanyDto {
  id: string;
  /** @nullable */
  tin: string | null;
  /** @nullable */
  email: string | null;
  registered_name: string;
  /** @nullable */
  company_type: string | null;
  /** @nullable */
  registered_address: string | null;
  cosmetic: CompanyDtoCosmetic;
  /** @nullable */
  is_deactivated: boolean | null;
}
