/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyCreateQueuedMoaDto } from "./companyCreateQueuedMoaDto";

export interface CompanyCreateQueuedMoaResponse {
  success: boolean;
  message?: string;
  queued: CompanyCreateQueuedMoaDto;
}
