/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type CompanyControllerRequestMoaBody = {
  universityId: string;
  templateId: string;
  repName: string;
  repTitle: string;
  repSignatureText?: string;
  invite_id?: string;
  signature?: Blob;
};
