/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyQueuedMoaListItemDtoUniversity } from "./companyQueuedMoaListItemDtoUniversity";
import type { CompanyQueuedMoaListItemDtoTemplate } from "./companyQueuedMoaListItemDtoTemplate";

export interface CompanyQueuedMoaListItemDto {
  id: string;
  status: string;
  /** @nullable */
  failure_reason: string | null;
  rep_name: string;
  rep_title: string;
  created_at: string;
  /** @nullable */
  university: CompanyQueuedMoaListItemDtoUniversity;
  /** @nullable */
  template: CompanyQueuedMoaListItemDtoTemplate;
}
