/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyPendingInviteDtoUniversity } from "./companyPendingInviteDtoUniversity";
import type { CompanyPendingInviteDtoTemplate } from "./companyPendingInviteDtoTemplate";

export interface CompanyPendingInviteDto {
  id: string;
  /** @nullable */
  university: CompanyPendingInviteDtoUniversity;
  /** @nullable */
  template: CompanyPendingInviteDtoTemplate;
}
