/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { CompanyRegisterInvitedResponseKind } from "./companyRegisterInvitedResponseKind";

export interface CompanyRegisterInvitedResponse {
  success: boolean;
  message?: string;
  university_id: string;
  /** @nullable */
  template_id: string | null;
  kind?: CompanyRegisterInvitedResponseKind;
  /** @nullable */
  magicLink?: string | null;
  conflictEmail?: string;
  autoLinkToken?: string;
}
