/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { PatchCompanyProfileDtoCompanyType } from "./patchCompanyProfileDtoCompanyType";

export interface PatchCompanyProfileDto {
  registered_name?: string;
  company_type?: PatchCompanyProfileDtoCompanyType;
  registered_address?: string;
  description?: string;
  website?: string;
  phone?: string;
  industry?: string;
}
