/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface PatchTemplateDto {
  name?: string;
  description?: string;
  field_schema?: string;
  /** Whether the template has no expiry */
  is_perpetual?: boolean;
  term_months?: number;
}
