/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type ResolveFileDtoKind =
  (typeof ResolveFileDtoKind)[keyof typeof ResolveFileDtoKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolveFileDtoKind = {
  signatory_signature: "signatory_signature",
  template_pdf: "template_pdf",
  moa_pdf: "moa_pdf",
} as const;
