/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { ResolveCompanyInviteResponseUniversity } from "./resolveCompanyInviteResponseUniversity";
import type { ResolveCompanyInviteResponseTemplate } from "./resolveCompanyInviteResponseTemplate";
import type { InviteDetailDto } from "./inviteDetailDto";

export interface ResolveCompanyInviteResponse {
  success: boolean;
  message?: string;
  university: ResolveCompanyInviteResponseUniversity;
  /** @nullable */
  template: ResolveCompanyInviteResponseTemplate;
  email: string;
  /** @nullable */
  company_name: string | null;
  invite_id: string;
  email_status: string;
  invite: InviteDetailDto;
}
