/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityLegacyCompanyDetailsDto } from "./universityLegacyCompanyDetailsDto";

export interface UniversityLegacyCompanySummaryDto {
  id: string;
  company_name: string;
  company_details: UniversityLegacyCompanyDetailsDto;
  moaCount: number;
  documentCount: number;
  /** @nullable */
  valid_until: string | null;
}
