/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface UniversityDto {
  id: string;
  registered_name: string;
  /** @nullable */
  logo_url: string | null;
  /** @nullable */
  address: string | null;
  /** @nullable */
  rep_name: string | null;
  /** @nullable */
  rep_title: string | null;
  /** @nullable */
  rep_signature_url: string | null;
}
