/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { BulkInviteTargetEchoDto } from "./bulkInviteTargetEchoDto";
import type { BulkInviteIssueDto } from "./bulkInviteIssueDto";
import type { BulkInviteCollapsedGroupDto } from "./bulkInviteCollapsedGroupDto";
import type { BulkInviteWarningsDto } from "./bulkInviteWarningsDto";

export interface UniversityBulkInviteResponse {
  success: boolean;
  message?: string;
  sent: boolean;
  willSend: BulkInviteTargetEchoDto[];
  blocked: BulkInviteIssueDto[];
  skipped: BulkInviteIssueDto[];
  collapsed: BulkInviteCollapsedGroupDto[];
  batchBlockers: string[];
  warnings: BulkInviteWarningsDto;
}
