/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityStaffAccountDtoRole } from "./universityStaffAccountDtoRole";

export interface UniversityStaffAccountDto {
  id: string;
  email: string;
  display_name: string;
  role: UniversityStaffAccountDtoRole;
  /** @nullable */
  is_deactivated: boolean | null;
  created_at: string;
  updated_at: string;
}
