/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityPartnerListItemDtoCompany } from "./universityPartnerListItemDtoCompany";

export interface UniversityPartnerListItemDto {
  /** @nullable */
  company: UniversityPartnerListItemDtoCompany;
  latestMoaId: string;
  latestMoaStatus: string;
  /** @nullable */
  effective_date: string | null;
  /** @nullable */
  expiry_date: string | null;
  /** @nullable */
  is_expired: boolean | null;
  hasActiveMoa: boolean;
  /** @nullable */
  lastRenewalRequestedAt: string | null;
}
