/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityLegacyCompanyDetailsDto } from "./universityLegacyCompanyDetailsDto";
import type { UniversityLegacyCompanyDocumentDto } from "./universityLegacyCompanyDocumentDto";
import type { UniversityLegacyCompanyMoaDto } from "./universityLegacyCompanyMoaDto";

export interface UniversityLegacyCompanyDetailDto {
  id: string;
  company_name: string;
  company_details: UniversityLegacyCompanyDetailsDto;
  company_documents: UniversityLegacyCompanyDocumentDto[];
  moas: UniversityLegacyCompanyMoaDto[];
}
