/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityTemplateDto } from "./universityTemplateDto";

export interface UniversityTemplateOfferDto {
  id: string;
  is_available: boolean;
  template: UniversityTemplateDto;
}
