/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityPartnerMoasCompanyDtoCosmetic } from "./universityPartnerMoasCompanyDtoCosmetic";
import type { UniversityPartnerMoasCompanyDtoDocumentReviewDetails } from "./universityPartnerMoasCompanyDtoDocumentReviewDetails";

export interface UniversityPartnerMoasCompanyDto {
  id: string;
  registered_name: string;
  /** @nullable */
  company_type: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  email_verified: boolean | null;
  /** @nullable */
  tin: string | null;
  /** @nullable */
  registered_address: string | null;
  cosmetic: UniversityPartnerMoasCompanyDtoCosmetic;
  document_review_details: UniversityPartnerMoasCompanyDtoDocumentReviewDetails;
  /** @nullable */
  is_deactivated: boolean | null;
  /** @nullable */
  iat_threshold: string | null;
  created_at: string;
  updated_at: string;
}
