/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface UniversityLegacyCompanyDocumentDto {
  id: string;
  type: string;
  filename: string;
  /** @nullable */
  url: string | null;
  /** @nullable */
  expiry_date: string | null;
  uploaded_at: string;
}
