/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityMoaDetailCompanyDto } from "./universityMoaDetailCompanyDto";
import type { UniversityMoaDetailMoaDtoTemplate } from "./universityMoaDetailMoaDtoTemplate";

export interface UniversityMoaDetailMoaDto {
  id: string;
  company_id: string;
  university_id: string;
  template_id: string;
  status: string;
  /** @nullable */
  is_expired: boolean | null;
  generated_pdf_url: string;
  effective_date: string;
  expiry_date: string;
  created_at: string;
  company: UniversityMoaDetailCompanyDto;
  /** @nullable */
  template: UniversityMoaDetailMoaDtoTemplate;
}
