/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityDto } from "./universityDto";

export interface UniversityUploadLogoResponse {
  success: boolean;
  message?: string;
  logo_url: string;
  university: UniversityDto;
}
