/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityRenewalListItemDtoStatus } from "./universityRenewalListItemDtoStatus";

export interface UniversityRenewalListItemDto {
  id: string;
  email: string;
  displayName: string;
  /** @nullable */
  companyId: string | null;
  requestedAt: string;
  status: UniversityRenewalListItemDtoStatus;
}
