/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export type UniversityControllerCreateLegacyCompanyBody = {
  company_name: string;
  moas: string;
  tin?: string;
  company_type?: string;
  registered_address?: string;
  contact_person?: string;
  contact_email?: string;
  contact_phone?: string;
  documentNames?: string;
  documentExpiryDates?: string;
  documentTypes?: string;
  moaDocuments?: Blob[];
  companyDocuments?: Blob[];
};
