/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityMoaDetailCompanyDtoCosmetic } from "./universityMoaDetailCompanyDtoCosmetic";
import type { UniversityMoaDetailCompanyDtoDocumentReviewDetails } from "./universityMoaDetailCompanyDtoDocumentReviewDetails";

export interface UniversityMoaDetailCompanyDto {
  id: string;
  registered_name: string;
  /** @nullable */
  company_type: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  email_verified: boolean | null;
  /** @nullable */
  tin: string | null;
  /** @nullable */
  registered_address: string | null;
  cosmetic: UniversityMoaDetailCompanyDtoCosmetic;
  document_review_details: UniversityMoaDetailCompanyDtoDocumentReviewDetails;
  /** @nullable */
  is_deactivated: boolean | null;
  /** @nullable */
  iat_threshold: string | null;
  created_at: string;
  updated_at: string;
}
