/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityBlacklistEntryDtoCompany } from "./universityBlacklistEntryDtoCompany";

export interface UniversityBlacklistEntryDto {
  id: string;
  company_id: string;
  university_id: string;
  /** @nullable */
  reason: string | null;
  created_at: string;
  /** @nullable */
  company: UniversityBlacklistEntryDtoCompany;
  /** @nullable */
  actor_email: string | null;
}
