/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityPartnerMoaItemDtoTemplate } from "./universityPartnerMoaItemDtoTemplate";

export interface UniversityPartnerMoaItemDto {
  id: string;
  status: string;
  created_at: string;
  effective_date: string;
  expiry_date: string;
  /** @nullable */
  is_expired: boolean | null;
  /** @nullable */
  template: UniversityPartnerMoaItemDtoTemplate;
}
