/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityPartnerCompanyDtoCosmetic } from "./universityPartnerCompanyDtoCosmetic";

export interface UniversityPartnerCompanyDto {
  id: string;
  registered_name: string;
  /** @nullable */
  company_type: string | null;
  cosmetic: UniversityPartnerCompanyDtoCosmetic;
}
