/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */

export interface UniversityAuditLogEntryDto {
  id: string;
  /** @nullable */
  actor_email: string | null;
  /** @nullable */
  company_id: string | null;
  /** @nullable */
  university_id: string | null;
  /** @nullable */
  moa_id: string | null;
  /** @nullable */
  platform_admin_id: string | null;
  event_type: string;
  /** @nullable */
  detail: string | null;
  created_at: string;
}
