/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityMoaDetailMoaDto } from "./universityMoaDetailMoaDto";
import type { UniversityMoaDetailDocumentDto } from "./universityMoaDetailDocumentDto";

export interface UniversityMoaDetailResponse {
  success: boolean;
  message?: string;
  moa: UniversityMoaDetailMoaDto;
  /** @nullable */
  pdfUrl: string | null;
  companyDocuments: UniversityMoaDetailDocumentDto[];
}
