/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import type { UniversityTemplateDtoFieldSchema } from "./universityTemplateDtoFieldSchema";

export interface UniversityTemplateDto {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  pdf_url: string;
  field_schema: UniversityTemplateDtoFieldSchema;
  term_months: number;
  page_count: number;
  page_w: number;
  page_h: number;
  /** @nullable */
  is_deleted: boolean | null;
  created_at: string;
  updated_at: string;
}
