/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  InviteControllerResolveCompanyInviteParams,
  ResolveCompanyInviteResponse,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const inviteControllerResolveCompanyInvite = (
  params?: InviteControllerResolveCompanyInviteParams,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<ResolveCompanyInviteResponse>({
    url: `/api/invite/company`,
    method: "GET",
    params,
    signal,
  });
};

export const getInviteControllerResolveCompanyInviteQueryKey = (
  params?: InviteControllerResolveCompanyInviteParams,
) => {
  return [`/api/invite/company`, ...(params ? [params] : [])] as const;
};

export const getInviteControllerResolveCompanyInviteQueryOptions = <
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getInviteControllerResolveCompanyInviteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>
  > = ({ signal }) => inviteControllerResolveCompanyInvite(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InviteControllerResolveCompanyInviteQueryResult = NonNullable<
  Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>
>;
export type InviteControllerResolveCompanyInviteQueryError = ErrorResponse;

export function useInviteControllerResolveCompanyInvite<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params: undefined | InviteControllerResolveCompanyInviteParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
          TError,
          Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerResolveCompanyInvite<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
          TError,
          Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerResolveCompanyInvite<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInviteControllerResolveCompanyInvite<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getInviteControllerResolveCompanyInviteQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getInviteControllerResolveCompanyInviteSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getInviteControllerResolveCompanyInviteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>
  > = ({ signal }) => inviteControllerResolveCompanyInvite(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InviteControllerResolveCompanyInviteSuspenseQueryResult =
  NonNullable<Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>>;
export type InviteControllerResolveCompanyInviteSuspenseQueryError =
  ErrorResponse;

export function useInviteControllerResolveCompanyInviteSuspense<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params: undefined | InviteControllerResolveCompanyInviteParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerResolveCompanyInviteSuspense<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInviteControllerResolveCompanyInviteSuspense<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInviteControllerResolveCompanyInviteSuspense<
  TData = Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
  TError = ErrorResponse,
>(
  params?: InviteControllerResolveCompanyInviteParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof inviteControllerResolveCompanyInvite>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getInviteControllerResolveCompanyInviteSuspenseQueryOptions(
      params,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
