/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { AdminLoginDto, BaseResponse, ErrorResponse } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const adminAuthControllerLogin = (
  adminLoginDto: AdminLoginDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/admin/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: adminLoginDto,
    signal,
  });
};

export const getAdminAuthControllerLoginMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLogin>>,
    TError,
    { data: AdminLoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>,
  TError,
  { data: AdminLoginDto },
  TContext
> => {
  const mutationKey = ["adminAuthControllerLogin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerLogin>>,
    { data: AdminLoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return adminAuthControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>
>;
export type AdminAuthControllerLoginMutationBody = AdminLoginDto;
export type AdminAuthControllerLoginMutationError = ErrorResponse;

export const useAdminAuthControllerLogin = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthControllerLogin>>,
      TError,
      { data: AdminLoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerLogin>>,
  TError,
  { data: AdminLoginDto },
  TContext
> => {
  const mutationOptions = getAdminAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminAuthControllerLogout = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/admin/logout`,
    method: "POST",
    signal,
  });
};

export const getAdminAuthControllerLogoutMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["adminAuthControllerLogout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminAuthControllerLogout>>,
    void
  > = () => {
    return adminAuthControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminAuthControllerLogout>>
>;

export type AdminAuthControllerLogoutMutationError = ErrorResponse;

export const useAdminAuthControllerLogout = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminAuthControllerLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adminAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAdminAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
