/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  ErrorResponse,
  UniversityAcceptInviteDto,
  UniversityForgotDto,
  UniversityLoginDto,
  UniversityResetDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const universityAuthControllerLogin = (
  universityLoginDto: UniversityLoginDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/university/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: universityLoginDto,
    signal,
  });
};

export const getUniversityAuthControllerLoginMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerLogin>>,
    TError,
    { data: UniversityLoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerLogin>>,
  TError,
  { data: UniversityLoginDto },
  TContext
> => {
  const mutationKey = ["universityAuthControllerLogin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerLogin>>,
    { data: UniversityLoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityAuthControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerLogin>>
>;
export type UniversityAuthControllerLoginMutationBody = UniversityLoginDto;
export type UniversityAuthControllerLoginMutationError = ErrorResponse;

export const useUniversityAuthControllerLogin = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerLogin>>,
      TError,
      { data: UniversityLoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerLogin>>,
  TError,
  { data: UniversityLoginDto },
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityAuthControllerLogout = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/university/logout`,
    method: "POST",
    signal,
  });
};

export const getUniversityAuthControllerLogoutMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["universityAuthControllerLogout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerLogout>>,
    void
  > = () => {
    return universityAuthControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerLogout>>
>;

export type UniversityAuthControllerLogoutMutationError = ErrorResponse;

export const useUniversityAuthControllerLogout = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityAuthControllerAcceptInvite = (
  universityAcceptInviteDto: UniversityAcceptInviteDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/university/accept-invite`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: universityAcceptInviteDto,
    signal,
  });
};

export const getUniversityAuthControllerAcceptInviteMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerAcceptInvite>>,
    TError,
    { data: UniversityAcceptInviteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerAcceptInvite>>,
  TError,
  { data: UniversityAcceptInviteDto },
  TContext
> => {
  const mutationKey = ["universityAuthControllerAcceptInvite"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerAcceptInvite>>,
    { data: UniversityAcceptInviteDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityAuthControllerAcceptInvite(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerAcceptInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerAcceptInvite>>
>;
export type UniversityAuthControllerAcceptInviteMutationBody =
  UniversityAcceptInviteDto;
export type UniversityAuthControllerAcceptInviteMutationError = ErrorResponse;

export const useUniversityAuthControllerAcceptInvite = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerAcceptInvite>>,
      TError,
      { data: UniversityAcceptInviteDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerAcceptInvite>>,
  TError,
  { data: UniversityAcceptInviteDto },
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerAcceptInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityAuthControllerForgot = (
  universityForgotDto: UniversityForgotDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/university/forgot`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: universityForgotDto,
    signal,
  });
};

export const getUniversityAuthControllerForgotMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerForgot>>,
    TError,
    { data: UniversityForgotDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerForgot>>,
  TError,
  { data: UniversityForgotDto },
  TContext
> => {
  const mutationKey = ["universityAuthControllerForgot"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerForgot>>,
    { data: UniversityForgotDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityAuthControllerForgot(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerForgotMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerForgot>>
>;
export type UniversityAuthControllerForgotMutationBody = UniversityForgotDto;
export type UniversityAuthControllerForgotMutationError = ErrorResponse;

export const useUniversityAuthControllerForgot = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerForgot>>,
      TError,
      { data: UniversityForgotDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerForgot>>,
  TError,
  { data: UniversityForgotDto },
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerForgotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const universityAuthControllerReset = (
  universityResetDto: UniversityResetDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/university/reset`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: universityResetDto,
    signal,
  });
};

export const getUniversityAuthControllerResetMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof universityAuthControllerReset>>,
    TError,
    { data: UniversityResetDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof universityAuthControllerReset>>,
  TError,
  { data: UniversityResetDto },
  TContext
> => {
  const mutationKey = ["universityAuthControllerReset"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof universityAuthControllerReset>>,
    { data: UniversityResetDto }
  > = (props) => {
    const { data } = props ?? {};

    return universityAuthControllerReset(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UniversityAuthControllerResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof universityAuthControllerReset>>
>;
export type UniversityAuthControllerResetMutationBody = UniversityResetDto;
export type UniversityAuthControllerResetMutationError = ErrorResponse;

export const useUniversityAuthControllerReset = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof universityAuthControllerReset>>,
      TError,
      { data: UniversityResetDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof universityAuthControllerReset>>,
  TError,
  { data: UniversityResetDto },
  TContext
> => {
  const mutationOptions =
    getUniversityAuthControllerResetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
