/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  ClaimInviteDto,
  CompanyClaimInviteResponse,
  CompanyControllerCreateQueuedMoaBody,
  CompanyControllerListMoasParams,
  CompanyControllerRequestMoaBody,
  CompanyControllerUploadDocumentBody,
  CompanyControllerUploadLogoBody,
  CompanyCreateQueuedMoaResponse,
  CompanyDocumentsResponse,
  CompanyMeResponse,
  CompanyMoaDetailResponse,
  CompanyMoasResponse,
  CompanyPatchProfileResponse,
  CompanyPendingInvitesResponse,
  CompanyQueuedMoasResponse,
  CompanyRequestMoaResponse,
  CompanyRequestableTemplatesResponse,
  CompanyUniversitiesResponse,
  CompanyUploadDocumentResponse,
  CompanyUploadLogoResponse,
  CompanyVerificationResponse,
  ErrorResponse,
  PatchCompanyProfileDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const companyControllerMe = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CompanyMeResponse>({
    url: `/api/company/me`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerMeQueryKey = () => {
  return [`/api/company/me`] as const;
};

export const getCompanyControllerMeQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof companyControllerMe>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompanyControllerMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerMe>>
  > = ({ signal }) => companyControllerMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerMe>>
>;
export type CompanyControllerMeQueryError = ErrorResponse;

export function useCompanyControllerMe<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerMe>>,
          TError,
          Awaited<ReturnType<typeof companyControllerMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerMe<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerMe>>,
          TError,
          Awaited<ReturnType<typeof companyControllerMe>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerMe<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerMe<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof companyControllerMe>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompanyControllerMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerMe>>
  > = ({ signal }) => companyControllerMe(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerMe>>
>;
export type CompanyControllerMeSuspenseQueryError = ErrorResponse;

export function useCompanyControllerMeSuspense<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerMeSuspense<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerMeSuspense<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerMeSuspense<
  TData = Awaited<ReturnType<typeof companyControllerMe>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerMe>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerMeSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerPatchProfile = (
  patchCompanyProfileDto: PatchCompanyProfileDto,
) => {
  return preconfiguredAxiosFunction<CompanyPatchProfileResponse>({
    url: `/api/company/profile`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchCompanyProfileDto,
  });
};

export const getCompanyControllerPatchProfileMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerPatchProfile>>,
    TError,
    { data: PatchCompanyProfileDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerPatchProfile>>,
  TError,
  { data: PatchCompanyProfileDto },
  TContext
> => {
  const mutationKey = ["companyControllerPatchProfile"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerPatchProfile>>,
    { data: PatchCompanyProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyControllerPatchProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerPatchProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerPatchProfile>>
>;
export type CompanyControllerPatchProfileMutationBody = PatchCompanyProfileDto;
export type CompanyControllerPatchProfileMutationError = ErrorResponse;

export const useCompanyControllerPatchProfile = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerPatchProfile>>,
      TError,
      { data: PatchCompanyProfileDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerPatchProfile>>,
  TError,
  { data: PatchCompanyProfileDto },
  TContext
> => {
  const mutationOptions =
    getCompanyControllerPatchProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyControllerGetVerification = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CompanyVerificationResponse>({
    url: `/api/company/verification`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerGetVerificationQueryKey = () => {
  return [`/api/company/verification`] as const;
};

export const getCompanyControllerGetVerificationQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof companyControllerGetVerification>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerGetVerificationQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetVerification>>
  > = ({ signal }) => companyControllerGetVerification(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetVerification>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetVerificationQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerGetVerification>>
>;
export type CompanyControllerGetVerificationQueryError = ErrorResponse;

export function useCompanyControllerGetVerification<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetVerification>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetVerification>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetVerification<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetVerification>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetVerification>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetVerification<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetVerification<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerGetVerificationQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerGetVerificationSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof companyControllerGetVerification>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerGetVerificationQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetVerification>>
  > = ({ signal }) => companyControllerGetVerification(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetVerification>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetVerificationSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerGetVerification>>
>;
export type CompanyControllerGetVerificationSuspenseQueryError = ErrorResponse;

export function useCompanyControllerGetVerificationSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetVerificationSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetVerificationSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetVerificationSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetVerification>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetVerification>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerGetVerificationSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerUploadLogo = (
  companyControllerUploadLogoBody: CompanyControllerUploadLogoBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, companyControllerUploadLogoBody.file);

  return preconfiguredAxiosFunction<CompanyUploadLogoResponse>({
    url: `/api/company/profile/logo`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getCompanyControllerUploadLogoMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerUploadLogo>>,
    TError,
    { data: CompanyControllerUploadLogoBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerUploadLogo>>,
  TError,
  { data: CompanyControllerUploadLogoBody },
  TContext
> => {
  const mutationKey = ["companyControllerUploadLogo"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerUploadLogo>>,
    { data: CompanyControllerUploadLogoBody }
  > = (props) => {
    const { data } = props ?? {};

    return companyControllerUploadLogo(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerUploadLogoMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerUploadLogo>>
>;
export type CompanyControllerUploadLogoMutationBody =
  CompanyControllerUploadLogoBody;
export type CompanyControllerUploadLogoMutationError = ErrorResponse;

export const useCompanyControllerUploadLogo = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerUploadLogo>>,
      TError,
      { data: CompanyControllerUploadLogoBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerUploadLogo>>,
  TError,
  { data: CompanyControllerUploadLogoBody },
  TContext
> => {
  const mutationOptions =
    getCompanyControllerUploadLogoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyControllerUploadDocument = (
  companyControllerUploadDocumentBody: CompanyControllerUploadDocumentBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, companyControllerUploadDocumentBody.file);
  formData.append(`type`, companyControllerUploadDocumentBody.type);

  return preconfiguredAxiosFunction<CompanyUploadDocumentResponse>({
    url: `/api/company/documents`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getCompanyControllerUploadDocumentMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerUploadDocument>>,
    TError,
    { data: CompanyControllerUploadDocumentBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerUploadDocument>>,
  TError,
  { data: CompanyControllerUploadDocumentBody },
  TContext
> => {
  const mutationKey = ["companyControllerUploadDocument"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerUploadDocument>>,
    { data: CompanyControllerUploadDocumentBody }
  > = (props) => {
    const { data } = props ?? {};

    return companyControllerUploadDocument(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerUploadDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerUploadDocument>>
>;
export type CompanyControllerUploadDocumentMutationBody =
  CompanyControllerUploadDocumentBody;
export type CompanyControllerUploadDocumentMutationError = ErrorResponse;

export const useCompanyControllerUploadDocument = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerUploadDocument>>,
      TError,
      { data: CompanyControllerUploadDocumentBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerUploadDocument>>,
  TError,
  { data: CompanyControllerUploadDocumentBody },
  TContext
> => {
  const mutationOptions =
    getCompanyControllerUploadDocumentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyControllerGetDocuments = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CompanyDocumentsResponse>({
    url: `/api/company/documents`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerGetDocumentsQueryKey = () => {
  return [`/api/company/documents`] as const;
};

export const getCompanyControllerGetDocumentsQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof companyControllerGetDocuments>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerGetDocumentsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetDocuments>>
  > = ({ signal }) => companyControllerGetDocuments(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetDocuments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetDocumentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerGetDocuments>>
>;
export type CompanyControllerGetDocumentsQueryError = ErrorResponse;

export function useCompanyControllerGetDocuments<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetDocuments>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetDocuments>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetDocuments<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetDocuments>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetDocuments>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetDocuments<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetDocuments<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerGetDocumentsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerGetDocumentsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof companyControllerGetDocuments>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerGetDocumentsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetDocuments>>
  > = ({ signal }) => companyControllerGetDocuments(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetDocuments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetDocumentsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerGetDocuments>>
>;
export type CompanyControllerGetDocumentsSuspenseQueryError = ErrorResponse;

export function useCompanyControllerGetDocumentsSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetDocumentsSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetDocumentsSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetDocumentsSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetDocuments>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetDocuments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerGetDocumentsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerListUniversities = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CompanyUniversitiesResponse>({
    url: `/api/company/universities`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerListUniversitiesQueryKey = () => {
  return [`/api/company/universities`] as const;
};

export const getCompanyControllerListUniversitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof companyControllerListUniversities>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListUniversitiesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListUniversities>>
  > = ({ signal }) => companyControllerListUniversities(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListUniversities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListUniversitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerListUniversities>>
>;
export type CompanyControllerListUniversitiesQueryError = ErrorResponse;

export function useCompanyControllerListUniversities<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListUniversities>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListUniversities>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListUniversities<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListUniversities>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListUniversities>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListUniversities<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListUniversities<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerListUniversitiesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerListUniversitiesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof companyControllerListUniversities>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListUniversitiesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListUniversities>>
  > = ({ signal }) => companyControllerListUniversities(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListUniversities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListUniversitiesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerListUniversities>>
>;
export type CompanyControllerListUniversitiesSuspenseQueryError = ErrorResponse;

export function useCompanyControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListUniversitiesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListUniversities>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListUniversities>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerListUniversitiesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerGetRequestableTemplates = (
  universityId: string | undefined | null,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyRequestableTemplatesResponse>({
    url: `/api/company/universities/${universityId}/templates`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerGetRequestableTemplatesQueryKey = (
  universityId?: string | undefined | null,
) => {
  return [`/api/company/universities/${universityId}/templates`] as const;
};

export const getCompanyControllerGetRequestableTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCompanyControllerGetRequestableTemplatesQueryKey(universityId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>
  > = ({ signal }) =>
    companyControllerGetRequestableTemplates(universityId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!universityId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetRequestableTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>
>;
export type CompanyControllerGetRequestableTemplatesQueryError = ErrorResponse;

export function useCompanyControllerGetRequestableTemplates<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetRequestableTemplates<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetRequestableTemplates<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetRequestableTemplates<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerGetRequestableTemplatesQueryOptions(
    universityId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerGetRequestableTemplatesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCompanyControllerGetRequestableTemplatesQueryKey(universityId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>
  > = ({ signal }) =>
    companyControllerGetRequestableTemplates(universityId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetRequestableTemplatesSuspenseQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>
  >;
export type CompanyControllerGetRequestableTemplatesSuspenseQueryError =
  ErrorResponse;

export function useCompanyControllerGetRequestableTemplatesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetRequestableTemplatesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetRequestableTemplatesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetRequestableTemplatesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
  TError = ErrorResponse,
>(
  universityId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetRequestableTemplates>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerGetRequestableTemplatesSuspenseQueryOptions(
      universityId,
      options,
    );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerRequestMoa = (
  companyControllerRequestMoaBody: CompanyControllerRequestMoaBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`universityId`, companyControllerRequestMoaBody.universityId);
  formData.append(`templateId`, companyControllerRequestMoaBody.templateId);
  formData.append(`repName`, companyControllerRequestMoaBody.repName);
  formData.append(`repTitle`, companyControllerRequestMoaBody.repTitle);
  if (companyControllerRequestMoaBody.repSignatureText !== undefined) {
    formData.append(
      `repSignatureText`,
      companyControllerRequestMoaBody.repSignatureText,
    );
  }
  if (companyControllerRequestMoaBody.invite_id !== undefined) {
    formData.append(`invite_id`, companyControllerRequestMoaBody.invite_id);
  }
  if (companyControllerRequestMoaBody.signature !== undefined) {
    formData.append(`signature`, companyControllerRequestMoaBody.signature);
  }

  return preconfiguredAxiosFunction<CompanyRequestMoaResponse>({
    url: `/api/company/moas`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getCompanyControllerRequestMoaMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerRequestMoa>>,
    TError,
    { data: CompanyControllerRequestMoaBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerRequestMoa>>,
  TError,
  { data: CompanyControllerRequestMoaBody },
  TContext
> => {
  const mutationKey = ["companyControllerRequestMoa"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerRequestMoa>>,
    { data: CompanyControllerRequestMoaBody }
  > = (props) => {
    const { data } = props ?? {};

    return companyControllerRequestMoa(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerRequestMoaMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerRequestMoa>>
>;
export type CompanyControllerRequestMoaMutationBody =
  CompanyControllerRequestMoaBody;
export type CompanyControllerRequestMoaMutationError = ErrorResponse;

export const useCompanyControllerRequestMoa = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerRequestMoa>>,
      TError,
      { data: CompanyControllerRequestMoaBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerRequestMoa>>,
  TError,
  { data: CompanyControllerRequestMoaBody },
  TContext
> => {
  const mutationOptions =
    getCompanyControllerRequestMoaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyControllerListMoas = (
  params?: CompanyControllerListMoasParams,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyMoasResponse>({
    url: `/api/company/moas`,
    method: "GET",
    params,
    signal,
  });
};

export const getCompanyControllerListMoasQueryKey = (
  params?: CompanyControllerListMoasParams,
) => {
  return [`/api/company/moas`, ...(params ? [params] : [])] as const;
};

export const getCompanyControllerListMoasQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListMoasQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListMoas>>
  > = ({ signal }) => companyControllerListMoas(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListMoas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListMoasQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerListMoas>>
>;
export type CompanyControllerListMoasQueryError = ErrorResponse;

export function useCompanyControllerListMoas<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params: undefined | CompanyControllerListMoasParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListMoas>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListMoas>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListMoas<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListMoas>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListMoas>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListMoas<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListMoas<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerListMoasQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerListMoasSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListMoasQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListMoas>>
  > = ({ signal }) => companyControllerListMoas(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListMoas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListMoasSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerListMoas>>
>;
export type CompanyControllerListMoasSuspenseQueryError = ErrorResponse;

export function useCompanyControllerListMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params: undefined | CompanyControllerListMoasParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListMoas>>,
  TError = ErrorResponse,
>(
  params?: CompanyControllerListMoasParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerListMoasSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerGetMoa = (
  moaId: string | undefined | null,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyMoaDetailResponse>({
    url: `/api/company/moas/${moaId}`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerGetMoaQueryKey = (
  moaId?: string | undefined | null,
) => {
  return [`/api/company/moas/${moaId}`] as const;
};

export const getCompanyControllerGetMoaQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerGetMoaQueryKey(moaId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetMoa>>
  > = ({ signal }) => companyControllerGetMoa(moaId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!moaId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetMoa>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetMoaQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerGetMoa>>
>;
export type CompanyControllerGetMoaQueryError = ErrorResponse;

export function useCompanyControllerGetMoa<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetMoa>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetMoa>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetMoa<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerGetMoa>>,
          TError,
          Awaited<ReturnType<typeof companyControllerGetMoa>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetMoa<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetMoa<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerGetMoaQueryOptions(moaId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerGetMoaSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerGetMoaQueryKey(moaId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerGetMoa>>
  > = ({ signal }) => companyControllerGetMoa(moaId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerGetMoa>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerGetMoaSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerGetMoa>>
>;
export type CompanyControllerGetMoaSuspenseQueryError = ErrorResponse;

export function useCompanyControllerGetMoaSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetMoaSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerGetMoaSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerGetMoaSuspense<
  TData = Awaited<ReturnType<typeof companyControllerGetMoa>>,
  TError = ErrorResponse,
>(
  moaId: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerGetMoa>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerGetMoaSuspenseQueryOptions(
    moaId,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerClaimInvite = (
  claimInviteDto: ClaimInviteDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyClaimInviteResponse>({
    url: `/api/company/invites/claim`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: claimInviteDto,
    signal,
  });
};

export const getCompanyControllerClaimInviteMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerClaimInvite>>,
    TError,
    { data: ClaimInviteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerClaimInvite>>,
  TError,
  { data: ClaimInviteDto },
  TContext
> => {
  const mutationKey = ["companyControllerClaimInvite"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerClaimInvite>>,
    { data: ClaimInviteDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyControllerClaimInvite(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerClaimInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerClaimInvite>>
>;
export type CompanyControllerClaimInviteMutationBody = ClaimInviteDto;
export type CompanyControllerClaimInviteMutationError = ErrorResponse;

export const useCompanyControllerClaimInvite = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerClaimInvite>>,
      TError,
      { data: ClaimInviteDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerClaimInvite>>,
  TError,
  { data: ClaimInviteDto },
  TContext
> => {
  const mutationOptions =
    getCompanyControllerClaimInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyControllerListPendingInvites = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CompanyPendingInvitesResponse>({
    url: `/api/company/invites/pending`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerListPendingInvitesQueryKey = () => {
  return [`/api/company/invites/pending`] as const;
};

export const getCompanyControllerListPendingInvitesQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListPendingInvitesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListPendingInvites>>
  > = ({ signal }) => companyControllerListPendingInvites(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListPendingInvitesQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerListPendingInvites>>
>;
export type CompanyControllerListPendingInvitesQueryError = ErrorResponse;

export function useCompanyControllerListPendingInvites<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListPendingInvites>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListPendingInvites<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListPendingInvites>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListPendingInvites<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListPendingInvites<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerListPendingInvitesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerListPendingInvitesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListPendingInvitesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListPendingInvites>>
  > = ({ signal }) => companyControllerListPendingInvites(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListPendingInvitesSuspenseQueryResult =
  NonNullable<Awaited<ReturnType<typeof companyControllerListPendingInvites>>>;
export type CompanyControllerListPendingInvitesSuspenseQueryError =
  ErrorResponse;

export function useCompanyControllerListPendingInvitesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListPendingInvitesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListPendingInvitesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListPendingInvitesSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListPendingInvites>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerListPendingInvitesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyControllerCreateQueuedMoa = (
  companyControllerCreateQueuedMoaBody: CompanyControllerCreateQueuedMoaBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(
    `universityId`,
    companyControllerCreateQueuedMoaBody.universityId,
  );
  formData.append(
    `templateId`,
    companyControllerCreateQueuedMoaBody.templateId,
  );
  formData.append(`repName`, companyControllerCreateQueuedMoaBody.repName);
  formData.append(`repTitle`, companyControllerCreateQueuedMoaBody.repTitle);
  if (companyControllerCreateQueuedMoaBody.repSignatureText !== undefined) {
    formData.append(
      `repSignatureText`,
      companyControllerCreateQueuedMoaBody.repSignatureText,
    );
  }
  if (companyControllerCreateQueuedMoaBody.invite_id !== undefined) {
    formData.append(
      `invite_id`,
      companyControllerCreateQueuedMoaBody.invite_id,
    );
  }
  if (companyControllerCreateQueuedMoaBody.signature !== undefined) {
    formData.append(
      `signature`,
      companyControllerCreateQueuedMoaBody.signature,
    );
  }

  return preconfiguredAxiosFunction<CompanyCreateQueuedMoaResponse>({
    url: `/api/company/queued-moas`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getCompanyControllerCreateQueuedMoaMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerCreateQueuedMoa>>,
    TError,
    { data: CompanyControllerCreateQueuedMoaBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerCreateQueuedMoa>>,
  TError,
  { data: CompanyControllerCreateQueuedMoaBody },
  TContext
> => {
  const mutationKey = ["companyControllerCreateQueuedMoa"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerCreateQueuedMoa>>,
    { data: CompanyControllerCreateQueuedMoaBody }
  > = (props) => {
    const { data } = props ?? {};

    return companyControllerCreateQueuedMoa(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerCreateQueuedMoaMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerCreateQueuedMoa>>
>;
export type CompanyControllerCreateQueuedMoaMutationBody =
  CompanyControllerCreateQueuedMoaBody;
export type CompanyControllerCreateQueuedMoaMutationError = ErrorResponse;

export const useCompanyControllerCreateQueuedMoa = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerCreateQueuedMoa>>,
      TError,
      { data: CompanyControllerCreateQueuedMoaBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerCreateQueuedMoa>>,
  TError,
  { data: CompanyControllerCreateQueuedMoaBody },
  TContext
> => {
  const mutationOptions =
    getCompanyControllerCreateQueuedMoaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyControllerListQueuedMoas = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CompanyQueuedMoasResponse>({
    url: `/api/company/queued-moas`,
    method: "GET",
    signal,
  });
};

export const getCompanyControllerListQueuedMoasQueryKey = () => {
  return [`/api/company/queued-moas`] as const;
};

export const getCompanyControllerListQueuedMoasQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListQueuedMoasQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListQueuedMoas>>
  > = ({ signal }) => companyControllerListQueuedMoas(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListQueuedMoasQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerListQueuedMoas>>
>;
export type CompanyControllerListQueuedMoasQueryError = ErrorResponse;

export function useCompanyControllerListQueuedMoas<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListQueuedMoas>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListQueuedMoas<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
          TError,
          Awaited<ReturnType<typeof companyControllerListQueuedMoas>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListQueuedMoas<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListQueuedMoas<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerListQueuedMoasQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyControllerListQueuedMoasSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerListQueuedMoasQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerListQueuedMoas>>
  > = ({ signal }) => companyControllerListQueuedMoas(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerListQueuedMoasSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerListQueuedMoas>>
>;
export type CompanyControllerListQueuedMoasSuspenseQueryError = ErrorResponse;

export function useCompanyControllerListQueuedMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListQueuedMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerListQueuedMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyControllerListQueuedMoasSuspense<
  TData = Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyControllerListQueuedMoas>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyControllerListQueuedMoasSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
