/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ErrorResponse,
  ResolveFileDto,
  ResolveFileResponse,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const filesControllerResolve = (
  resolveFileDto: ResolveFileDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<ResolveFileResponse>({
    url: `/api/files/resolve`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: resolveFileDto,
    signal,
  });
};

export const getFilesControllerResolveMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesControllerResolve>>,
    TError,
    { data: ResolveFileDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesControllerResolve>>,
  TError,
  { data: ResolveFileDto },
  TContext
> => {
  const mutationKey = ["filesControllerResolve"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerResolve>>,
    { data: ResolveFileDto }
  > = (props) => {
    const { data } = props ?? {};

    return filesControllerResolve(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilesControllerResolveMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerResolve>>
>;
export type FilesControllerResolveMutationBody = ResolveFileDto;
export type FilesControllerResolveMutationError = ErrorResponse;

export const useFilesControllerResolve = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesControllerResolve>>,
      TError,
      { data: ResolveFileDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filesControllerResolve>>,
  TError,
  { data: ResolveFileDto },
  TContext
> => {
  const mutationOptions = getFilesControllerResolveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
