/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BetterInternship IOM API
 * IOM Platform API — MOA management between companies (HTEs) and universities (HEIs).
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  CompanyAuthListResponse,
  CompanyForgotDto,
  CompanyForgotResponse,
  CompanyLoginDto,
  CompanyLoginInviteResponse,
  CompanyOtpRequestDto,
  CompanyOtpRequestResponse,
  CompanyOtpVerifyDto,
  CompanyRegisterDto,
  CompanyRegisterInvitedResponse,
  CompanyRegisterResponse,
  CompanyResetDto,
  ErrorResponse,
  LoginViaInviteDto,
  RegisterInvitedCompanyDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const companyAuthControllerList = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CompanyAuthListResponse>({
    url: `/api/auth/company/list`,
    method: "GET",
    signal,
  });
};

export const getCompanyAuthControllerListQueryKey = () => {
  return [`/api/auth/company/list`] as const;
};

export const getCompanyAuthControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof companyAuthControllerList>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyAuthControllerListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyAuthControllerList>>
  > = ({ signal }) => companyAuthControllerList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyAuthControllerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyAuthControllerListQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerList>>
>;
export type CompanyAuthControllerListQueryError = ErrorResponse;

export function useCompanyAuthControllerList<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyAuthControllerList>>,
          TError,
          Awaited<ReturnType<typeof companyAuthControllerList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyAuthControllerList<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyAuthControllerList>>,
          TError,
          Awaited<ReturnType<typeof companyAuthControllerList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyAuthControllerList<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyAuthControllerList<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyAuthControllerListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyAuthControllerListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof companyAuthControllerList>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyAuthControllerListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyAuthControllerList>>
  > = ({ signal }) => companyAuthControllerList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companyAuthControllerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyAuthControllerListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerList>>
>;
export type CompanyAuthControllerListSuspenseQueryError = ErrorResponse;

export function useCompanyAuthControllerListSuspense<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyAuthControllerListSuspense<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyAuthControllerListSuspense<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCompanyAuthControllerListSuspense<
  TData = Awaited<ReturnType<typeof companyAuthControllerList>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companyAuthControllerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCompanyAuthControllerListSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const companyAuthControllerRegister = (
  companyRegisterDto: CompanyRegisterDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyRegisterResponse>({
    url: `/api/auth/company/register`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyRegisterDto,
    signal,
  });
};

export const getCompanyAuthControllerRegisterMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerRegister>>,
    TError,
    { data: CompanyRegisterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>,
  TError,
  { data: CompanyRegisterDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerRegister"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerRegister>>,
    { data: CompanyRegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>
>;
export type CompanyAuthControllerRegisterMutationBody = CompanyRegisterDto;
export type CompanyAuthControllerRegisterMutationError = ErrorResponse;

export const useCompanyAuthControllerRegister = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerRegister>>,
      TError,
      { data: CompanyRegisterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerRegister>>,
  TError,
  { data: CompanyRegisterDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerOtpRequest = (
  companyOtpRequestDto: CompanyOtpRequestDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyOtpRequestResponse>({
    url: `/api/auth/company/otp/request`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyOtpRequestDto,
    signal,
  });
};

export const getCompanyAuthControllerOtpRequestMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
    TError,
    { data: CompanyOtpRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
  TError,
  { data: CompanyOtpRequestDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerOtpRequest"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
    { data: CompanyOtpRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerOtpRequest(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerOtpRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>
>;
export type CompanyAuthControllerOtpRequestMutationBody = CompanyOtpRequestDto;
export type CompanyAuthControllerOtpRequestMutationError = ErrorResponse;

export const useCompanyAuthControllerOtpRequest = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
      TError,
      { data: CompanyOtpRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerOtpRequest>>,
  TError,
  { data: CompanyOtpRequestDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerOtpRequestMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerOtpVerify = (
  companyOtpVerifyDto: CompanyOtpVerifyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/company/otp/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyOtpVerifyDto,
    signal,
  });
};

export const getCompanyAuthControllerOtpVerifyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
    TError,
    { data: CompanyOtpVerifyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
  TError,
  { data: CompanyOtpVerifyDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerOtpVerify"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
    { data: CompanyOtpVerifyDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerOtpVerify(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerOtpVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>
>;
export type CompanyAuthControllerOtpVerifyMutationBody = CompanyOtpVerifyDto;
export type CompanyAuthControllerOtpVerifyMutationError = ErrorResponse;

export const useCompanyAuthControllerOtpVerify = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
      TError,
      { data: CompanyOtpVerifyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerOtpVerify>>,
  TError,
  { data: CompanyOtpVerifyDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerOtpVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLogin = (
  companyLoginDto: CompanyLoginDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/company/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyLoginDto,
    signal,
  });
};

export const getCompanyAuthControllerLoginMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLogin>>,
    TError,
    { data: CompanyLoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLogin>>,
  TError,
  { data: CompanyLoginDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerLogin"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLogin>>,
    { data: CompanyLoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLogin>>
>;
export type CompanyAuthControllerLoginMutationBody = CompanyLoginDto;
export type CompanyAuthControllerLoginMutationError = ErrorResponse;

export const useCompanyAuthControllerLogin = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLogin>>,
      TError,
      { data: CompanyLoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLogin>>,
  TError,
  { data: CompanyLoginDto },
  TContext
> => {
  const mutationOptions = getCompanyAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLogout = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/company/logout`,
    method: "POST",
    signal,
  });
};

export const getCompanyAuthControllerLogoutMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["companyAuthControllerLogout"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLogout>>,
    void
  > = () => {
    return companyAuthControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>
>;

export type CompanyAuthControllerLogoutMutationError = ErrorResponse;

export const useCompanyAuthControllerLogout = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerForgot = (
  companyForgotDto: CompanyForgotDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyForgotResponse>({
    url: `/api/auth/company/forgot`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyForgotDto,
    signal,
  });
};

export const getCompanyAuthControllerForgotMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerForgot>>,
    TError,
    { data: CompanyForgotDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerForgot>>,
  TError,
  { data: CompanyForgotDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerForgot"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerForgot>>,
    { data: CompanyForgotDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerForgot(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerForgotMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerForgot>>
>;
export type CompanyAuthControllerForgotMutationBody = CompanyForgotDto;
export type CompanyAuthControllerForgotMutationError = ErrorResponse;

export const useCompanyAuthControllerForgot = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerForgot>>,
      TError,
      { data: CompanyForgotDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerForgot>>,
  TError,
  { data: CompanyForgotDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerForgotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerRegisterInvited = (
  registerInvitedCompanyDto: RegisterInvitedCompanyDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyRegisterInvitedResponse>({
    url: `/api/auth/company/register-invited`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: registerInvitedCompanyDto,
    signal,
  });
};

export const getCompanyAuthControllerRegisterInvitedMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
    TError,
    { data: RegisterInvitedCompanyDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
  TError,
  { data: RegisterInvitedCompanyDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerRegisterInvited"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
    { data: RegisterInvitedCompanyDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerRegisterInvited(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerRegisterInvitedMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>
>;
export type CompanyAuthControllerRegisterInvitedMutationBody =
  RegisterInvitedCompanyDto;
export type CompanyAuthControllerRegisterInvitedMutationError = ErrorResponse;

export const useCompanyAuthControllerRegisterInvited = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
      TError,
      { data: RegisterInvitedCompanyDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerRegisterInvited>>,
  TError,
  { data: RegisterInvitedCompanyDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerRegisterInvitedMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerLoginViaInvite = (
  loginViaInviteDto: LoginViaInviteDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<CompanyLoginInviteResponse>({
    url: `/api/auth/company/login-invite`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: loginViaInviteDto,
    signal,
  });
};

export const getCompanyAuthControllerLoginViaInviteMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
    TError,
    { data: LoginViaInviteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
  TError,
  { data: LoginViaInviteDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerLoginViaInvite"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
    { data: LoginViaInviteDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerLoginViaInvite(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerLoginViaInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>
>;
export type CompanyAuthControllerLoginViaInviteMutationBody = LoginViaInviteDto;
export type CompanyAuthControllerLoginViaInviteMutationError = ErrorResponse;

export const useCompanyAuthControllerLoginViaInvite = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
      TError,
      { data: LoginViaInviteDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerLoginViaInvite>>,
  TError,
  { data: LoginViaInviteDto },
  TContext
> => {
  const mutationOptions =
    getCompanyAuthControllerLoginViaInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const companyAuthControllerReset = (
  companyResetDto: CompanyResetDto,
  signal?: AbortSignal,
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/auth/company/reset`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: companyResetDto,
    signal,
  });
};

export const getCompanyAuthControllerResetMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyAuthControllerReset>>,
    TError,
    { data: CompanyResetDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyAuthControllerReset>>,
  TError,
  { data: CompanyResetDto },
  TContext
> => {
  const mutationKey = ["companyAuthControllerReset"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyAuthControllerReset>>,
    { data: CompanyResetDto }
  > = (props) => {
    const { data } = props ?? {};

    return companyAuthControllerReset(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyAuthControllerResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyAuthControllerReset>>
>;
export type CompanyAuthControllerResetMutationBody = CompanyResetDto;
export type CompanyAuthControllerResetMutationError = ErrorResponse;

export const useCompanyAuthControllerReset = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyAuthControllerReset>>,
      TError,
      { data: CompanyResetDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyAuthControllerReset>>,
  TError,
  { data: CompanyResetDto },
  TContext
> => {
  const mutationOptions = getCompanyAuthControllerResetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
