# repo: neue-dev/IOM-Client-Dev
name: Sync to Deployment Fork

on:
  push:
    branches:
      - main # Release branch

jobs:
  call-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger sync in fork
        run: |
          curl -X POST https://api.github.com/repos/neue-dev/IOM-Client/actions/workflows/304108392/dispatches \
            -H "Authorization: token ${{ secrets.DEPLOY_FORK_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"ref":"main"}'
